name: signalr_core
description: ASP.NET Core SignalR Client written for Dart that is platform-independent, and can be used on both the command-line and the browser.
version: 1.1.0
publish_to: none
homepage: https://github.com/jamiewest/signalr_core

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.0
  logging: ^1.0.0
  meta: ^1.3.0
  tuple: ^2.0.0-nullsafety.0
  web_socket_channel: ^2.0.0
  sse_client:
    git:
      url: https://github.com/Mol0ko/sse_client
  equatable: ^2.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
