name: signalr_core
description: ASP.NET Core SignalR Client written for Dart that is platform-independent, and can be used on both the command-line and the browser.
version: 1.0.5
homepage: https://github.com/jamiewest/signalr_core

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  http: ^0.12.1
  logging: ^0.11.4
  meta: ^1.1.8
  tuple: ^1.0.3
  web_socket_channel: ^1.1.0
  sse_client: ^0.0.3

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.2.0
